<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>markdown</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~M</string>
	<key>name</key>
	<string>Github Flavored Markdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#markdown_block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ampersand</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bracket</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bold</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#italic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-citation</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#image-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-email</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inet</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-inline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-bare</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-footnote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-ref-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#latex-math</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-include</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#inline-liquid</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.brace.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.brace.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>attributes.markdown.mdk</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s\[\{])(?:#|\.)[a-zA-Z0-9\-:_]+</string>
					<key>name</key>
					<string>constant.other.symbol.id.markdown.mdk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s\[\{])(?:@|\.)[a-zA-Z0-9\-:_]+</string>
					<key>name</key>
					<string>constant.other.symbol.id.markdown.mdk</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\[[^\[\]]*?\]{.todo}|\[(?:todo|TODO):\s*.*?\]</string>
					<key>name</key>
					<string>entity.todo.markdown</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>ampersand</key>
				<dict>
					<key>comment</key>
					<string>
						Markdown will convert this for us. We match it so that the
						HTML grammar will not mark it up as invalid.
					</string>
					<key>match</key>
					<string>&amp;(?!([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+);)</string>
					<key>name</key>
					<string>meta.other.valid-ampersand.markdown</string>
				</dict>
				<key>bold</key>
				<dict>
					<key>begin</key>
					<string>(?x)
								(\*\*|__)(?=\S)								# Open
								(?=
									(
									    &lt;[^&gt;]*+&gt;							# HTML tags
									  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																			# Raw
									  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
									  | \[
										(				
										        (?&lt;square&gt;					# Named group
													[^\[\]\\]				# Match most chars
										          | \\.						# Escaped chars
										          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
										        )*+
											\]
											(
												(							# Reference Link
													[ ]?					# Optional space
													\[[^\]]*+\]				# Ref name
												)
											  | (							# Inline Link
													\(						# Opening paren
														[ \t]*+				# Optional whtiespace
														&lt;?(.*?)&gt;?			# URL
														[ \t]*+				# Optional whtiespace
														(					# Optional Title
															(?&lt;title&gt;['"])
															(.*?)
															\k&lt;title&gt;
														)?
													\)
												)
											)
										)
									  | (?!(?&lt;=\S)\1).						# Everything besides
																			# style closer
									)++
									(?&lt;=\S)\1								# Close
								)
							</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.bold.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\S)(\1)</string>
					<key>name</key>
					<string>markup.bold.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>applyEndPatternLast</key>
							<integer>1</integer>
							<key>begin</key>
							<string>(?=&lt;[^&gt;]*?&gt;)</string>
							<key>end</key>
							<string>(?&lt;=&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.basic</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ampersand</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bracket</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#italic</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#image-inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-bare</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-inet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-email</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#image-ref</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-footnote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-ref-literal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-ref</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-citation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-include</string>
						</dict>
					</array>
				</dict>
				<key>bracket</key>
				<dict>
					<key>comment</key>
					<string>
						Markdown will convert this for us. We match it so that the
						HTML grammar will not mark it up as invalid.
					</string>
					<key>match</key>
					<string>&lt;(?![a-z/?\$!])</string>
					<key>name</key>
					<string>meta.other.valid-bracket.markdown</string>
				</dict>
				<key>escape</key>
				<dict>
					<key>match</key>
					<string>\\[-`*_#+.!(){}\[\]\\&gt;]</string>
					<key>name</key>
					<string>constant.character.escape.markdown</string>
				</dict>
				<key>image-inline</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.markdown</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.markdown</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>14</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.markdown</string>
						</dict>
						<key>15</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.markdown</string>
						</dict>
						<key>16</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.metadata.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.whitespace.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.metadata.markdown</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.image.markdown</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x:
						\!							# Images start with !
						(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])	
													# Match the link text.
						([ ])?						# Space not allowed
						(\()						# Opening paren for url
							(&lt;?)(\S+?)(&gt;?)			# The url
							[ \t]*					# Optional whitespace
							(?:
								  ((\().+?(\)))		# Match title in parens…
								| ((").+?("))		# or in quotes.
							)?						# Title is optional
							\s*						# Optional whitespace
						(\))
					 )</string>
					<key>name</key>
					<string>meta.image.inline.markdown</string>
				</dict>
				<key>image-ref</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.link.markdown</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\!(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)(.*?)(\])</string>
					<key>name</key>
					<string>meta.image.reference.markdown</string>
				</dict>
				<key>inline-liquid</key>
				<dict>
					<key>begin</key>
					<string>\{(?:%|\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?:%|\})\}</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.tex</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.other.liquid.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\\$</string>
							<key>name</key>
							<string>constant.character.escape.tex</string>
						</dict>
					</array>
				</dict>
				<key>italic</key>
				<dict>
					<key>begin</key>
					<string>(?x)
								(\*|_)(?=\S)								# Open
								(?=
									(
									    &lt;[^&gt;]*+&gt;							# HTML tags
									  | (?&lt;raw&gt;`+)([^`]|(?!(?&lt;!`)\k&lt;raw&gt;(?!`))`)*+\k&lt;raw&gt;
																			# Raw
									  | \\[\\`*_{}\[\]()#.!+\-&gt;]?+			# Escapes
									  | \[
										(				
										        (?&lt;square&gt;					# Named group
													[^\[\]\\]				# Match most chars
										          | \\.						# Escaped chars
										          | \[ \g&lt;square&gt;*+ \]		# Nested brackets
										        )*+
											\]
											(
												(							# Reference Link
													[ ]?					# Optional space
													\[[^\]]*+\]				# Ref name
												)
											  | (							# Inline Link
													\(						# Opening paren
														[ \t]*+				# Optional whtiespace
														&lt;?(.*?)&gt;?			# URL
														[ \t]*+				# Optional whtiespace
														(					# Optional Title
															(?&lt;title&gt;['"])
															(.*?)
															\k&lt;title&gt;
														)?
													\)
												)
											)
										)
									  | \1\1								# Must be bold closer
									  | (?!(?&lt;=\S)\1).						# Everything besides
																			# style closer
									)++
									(?&lt;=\S)\1								# Close
								)
							</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.italic.markdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?&lt;=\S)(\1)((?!\1)|(?=\1\1))</string>
					<key>name</key>
					<string>markup.italic.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>applyEndPatternLast</key>
							<integer>1</integer>
							<key>begin</key>
							<string>(?=&lt;[^&gt;]*?&gt;)</string>
							<key>end</key>
							<string>(?&lt;=&gt;)</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.basic</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>include</key>
							<string>#escape</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ampersand</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bracket</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#raw</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bold</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#image-inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-bare</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-inet</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-email</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#image-ref</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-footnote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-ref-literal</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-ref</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-citation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#link-include</string>
						</dict>
					</array>
				</dict>
				<key>latex-block</key>
				<dict>
					<key>begin</key>
					<string>(\\begin)(\{)(\w+)(\}).*$</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.embedded.latex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.latex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.parameter.function.latex</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.latex</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.block.embedded.latex</string>
					<key>end</key>
					<string>(\\end)(\{)(\w+)(\})</string>
					<key>name</key>
					<string>meta.block.embedded.latex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#latex-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#latex-function</string>
						</dict>
					</array>
				</dict>
				<key>latex-function</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.embedded.latex</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.latex</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.latex</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\\\w+)(\{).*?(\})</string>
					<key>name</key>
					<string>meta.function.embedded.latex</string>
				</dict>
				<key>latex-math</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.other.math.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.math.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.other.math.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\$)(.*?)(\$)</string>
					<key>name</key>
					<string>meta.math.markdown</string>
				</dict>
				<key>link-bare</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>&lt;?(\w{3,}://[^&gt; \t]+)&gt;?</string>
					<key>name</key>
					<string>meta.link.bare.markdown</string>
				</dict>
				<key>link-citation</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.symbol.citation.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant.other.symbol.citation.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)\s*(([@#^][\w:\-_.]*;?\s*)+)\s*(\])</string>
					<key>name</key>
					<string>meta.link.citation.inline.markdown</string>
				</dict>
				<key>link-email</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;)((?:mailto:)?[-.\w]+@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)(&gt;)</string>
					<key>name</key>
					<string>meta.link.email.lt-gt.markdown</string>
				</dict>
				<key>link-footnote</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>markup.italic.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)(\^[a-zA-Z0-9._-]+)(\])(:)\s*(.*)$</string>
					<key>name</key>
					<string>meta.link.footnote.markdown</string>
				</dict>
				<key>link-include</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.other.madoko.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.other.link.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)\s*(INCLUDE|TOC|FOOTNOTES|BIB|TITLE)((=)(".*"))?\s*(\])</string>
					<key>name</key>
					<string>meta.link.include.markdown</string>
				</dict>
				<key>link-inet</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(&lt;)((?:https?|ftp)://.*?)(&gt;)</string>
					<key>name</key>
					<string>meta.link.inet.markdown</string>
				</dict>
				<key>link-inline</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>14</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>15</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>16</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.metadata.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.whitespace.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.metadata.markdown</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?x:
						(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])	
													# Match the link text.
						([ ])?						# Space not allowed
						(\()						# Opening paren for url
							(&lt;?)(.*?)(&gt;?)			# The url
							[ \t]*					# Optional whitespace
							(?:
								  ((\().+?(\)))		# Match title in parens…
								| ((").+?("))		# or in quotes.
							)?						# Title is optional
							\s*						# Optional whitespace
						(\))
					 )</string>
					<key>name</key>
					<string>meta.link.inline.markdown</string>
				</dict>
				<key>link-ref</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.begin.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.link.markdown</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.end.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)([^\]]*+)(\])</string>
					<key>name</key>
					<string>meta.link.reference.markdown</string>
				</dict>
				<key>link-ref-literal</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.other.link.title.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.begin.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.end.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\[)((?&lt;square&gt;[^\[\]\\]|\\.|\[\g&lt;square&gt;*+\])*+)(\])[ ]?(\[)(\])</string>
					<key>name</key>
					<string>meta.link.reference.literal.markdown</string>
				</dict>
				<key>raw</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.markdown</string>
						</dict>
						<key>2</key>
						<dict/>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(`+)([^`]|(?!(?&lt;!`)\1(?!`))`)*+(\1)</string>
					<key>name</key>
					<string>markup.raw.inline.markdown</string>
				</dict>
			</dict>
		</dict>
		<key>markdown_block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#frontmatter</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#heading</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockquote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded_code</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw_block_github</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#madoko_float</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lists</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paragraph</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>blockquote</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)(&gt;) ?</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.quote.markdown</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.quote.body.markdown</string>
					<key>name</key>
					<string>markup.quote.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#markdown_block</string>
						</dict>
					</array>
					<key>while</key>
					<string>(^|\G)(&gt;) ?</string>
				</dict>
				<key>embedded_code</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*python$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.python.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.python</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*ruby$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.ruby.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.ruby</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*scala$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.scala.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.scala</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*(?:cpp|c++)$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.c++.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.embed.c</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*(?:x86|asm)$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.x86.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.asm.x86</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*\{?r.*\}?$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.r.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.r</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*llvm$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.c++.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.llvm</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*c$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.c.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.embed.c</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*java$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.java.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.java</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*css$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.css.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.css</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*go$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.java.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.go</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*sql$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.sql.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.sql</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*js$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.java.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.js</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)\s*[`~]{3,}\s*(bash|sh)$\n</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.raw.block.bash.markdown</string>
							<key>end</key>
							<string>[`~]{3,}\n</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>markup.raw.border.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.shell</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<key>frontmatter</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(\A)(---\n)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.separator.frontmatter.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>meta.frontmatter.markdown</string>
							<key>end</key>
							<string>(^)(---\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.separator.frontmatter.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.yaml</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\A)(\+\+\+\n)</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.separator.frontmatter.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>meta.frontmatter.markdown</string>
							<key>end</key>
							<string>(^)(\+\+\+\n)</string>
							<key>endCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>meta.separator.frontmatter.markdown</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.toml</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\A)([\w ]*?:)(.*)$</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.yaml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.yaml</string>
								</dict>
							</dict>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.yaml</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.yaml</string>
								</dict>
							</dict>
							<key>name</key>
							<string>meta.frontmatter.markdown</string>
							<key>while</key>
							<string>(^)(?:(.*?:)(.*)|(\s*))$</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.yaml</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>string.unquoted.yaml</string>
								</dict>
							</dict>
							<key>match</key>
							<string>~([\w ]*?)\s*:(.*)$</string>
							<key>name</key>
							<string>meta.frontmatter.markdown</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(@html\s*)?(\.[\w-]+|\w+)\s*{</string>
							<key>captures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.yaml</string>
								</dict>
							</dict>
							<key>end</key>
							<string>}</string>
							<key>name</key>
							<string>meta.frontmatter.css.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>captures</key>
									<dict>
										<key>1</key>
										<dict>
											<key>name</key>
											<string>entity.name.tag.yaml</string>
										</dict>
										<key>3</key>
										<dict>
											<key>name</key>
											<string>string.unquoted.yaml</string>
										</dict>
									</dict>
									<key>match</key>
									<string>([\w-]+)\s*(=|:)\s*('.*?'|".*?"|[^ ]+)</string>
									<key>name</key>
									<string>meta.inner.yaml</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\.\w+</string>
									<key>name</key>
									<string>constant.other.symbol.inner.css</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>^((?:\w+\s+){0,2}(?:\w+)):$</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.tag.yaml</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>string.unquoted.yaml</string>
							<key>name</key>
							<string>meta.frontmatter.multiline.yaml</string>
							<key>while</key>
							<string>^\t</string>
						</dict>
					</array>
				</dict>
				<key>heading</key>
				<dict>
					<key>begin</key>
					<string>^(#{1,6})(\s*)(?=[\S[^#]])</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>entity.title.${1/(#)(#)?(#)?(#)?(#)?(#)?/${6:?6:${5:?5:${4:?4:${3:?3:${2:?2:1}}}}}/}.markdown</string>
					<key>end</key>
					<string>\s*(#{1,6})?$\n?</string>
					<key>name</key>
					<string>markup.heading.${1/(#)(#)?(#)?(#)?(#)?(#)?/${6:?6:${5:?5:${4:?4:${3:?3:${2:?2:1}}}}}/}.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
					</array>
				</dict>
				<key>heading-alt</key>
				<dict>
					<key>begin</key>
					<string>(?x)^([\w:]+(?:\s|$))+$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.title.1.markdown</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.heading.1.markdown</string>
					<key>while</key>
					<string>(?x)^-{3,}</string>
				</dict>
				<key>heading2-alt</key>
				<dict>
					<key>begin</key>
					<string>(?x)^([\w:]+(?:\s|$))+$</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.title.2.markdown</string>
						</dict>
					</dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.heading.markdown</string>
						</dict>
					</dict>
					<key>name</key>
					<string>markup.heading.1.markdown</string>
					<key>while</key>
					<string>(?x)^={3,}</string>
				</dict>
				<key>html</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>&lt;!---</string>
							<key>end</key>
							<string>---&gt;</string>
							<key>name</key>
							<string>comment.block.html</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)(^|\G)(?=&lt;(p|div|h[1-6]|style|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del).*&lt;/\2\s*&gt;\s*$)</string>
							<key>contentName</key>
							<string>source.embedded.html</string>
							<key>end</key>
							<string>$</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.basic</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?i)(^|\G)(?=&lt;(p|div|h[1-6]|blockquote|pre|table|dl|ol|ul|script|noscript|form|fieldset|iframe|math|ins|del))</string>
							<key>contentName</key>
							<string>source.embedded.html</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.html.basic</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G(?!&lt;/\2\s*&gt;)</string>
						</dict>
					</array>
				</dict>
				<key>link-def</key>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>11</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>12</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
						<key>13</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.markdown</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.other.reference.link.markdown</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.constant.markdown</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.markdown</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>markup.underline.link.markdown</string>
						</dict>
						<key>7</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.link.markdown</string>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>string.other.link.description.title.markdown</string>
						</dict>
						<key>9</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.markdown</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(?x:
									\s*						# Leading whitespace
									(\[)(.+?)(\])(:)		# Reference name
									[ \t]*					# Optional whitespace
									(&lt;?)(\S+?)(&gt;?)			# The url
									[ \t]*					# Optional whitespace
									(?:
										  ((\().+?(\)))		# Match title in quotes…
										| ((").+?("))		# or in parens.
									)?						# Title is optional
									\s*						# Optional whitespace
									$
								)</string>
					<key>name</key>
					<string>meta.link.reference.def.markdown</string>
				</dict>
				<key>list_paragraph</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)(?=\S)(?![*+-]\s|[0-9]+\.\s)</string>
					<key>name</key>
					<string>meta.paragraph.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#heading-setext</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#markdown_block</string>
						</dict>
					</array>
					<key>while</key>
					<string>(^|\G)(?!\s*$|#|[ ]{,3}([-*_][ ]{2,}){3,}[ \t]*$\n?|&gt;|[ ]{0,3}[*+-]|[ ]{0,3}[0-9]+\.)</string>
				</dict>
				<key>lists</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([*+-]) (\[ ?\])([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.list.unordered.markdown</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.list.todobox.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.list.todo.incomplete.markdown</string>
							<key>name</key>
							<string>markup.list.unordered.todo.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list_paragraph</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#markdown_block</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G([ ]{4}|\t|$)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([*+-]) (\[x\])([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.list.unordered.markdown</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>punctuation.list.todobox.markdown</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>markup.list.todo.completed.markdown</string>
							<key>name</key>
							<string>markup.list.unordered.todo.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list_paragraph</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#markdown_block</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G([ ]{4}|\t|$)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([*+-])([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.list.unordered.markdown</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>Currently does not support un-indented second lines.</string>
							<key>name</key>
							<string>markup.list.unordered.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list_paragraph</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#markdown_block</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G([ ]{4}|\t|$)</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(^|\G)([ ]{0,3})([0-9]+\.)([ ]{1,3}|\t)</string>
							<key>beginCaptures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>punctuation.list.ordered.markdown</string>
								</dict>
							</dict>
							<key>name</key>
							<string>markup.list.numbered.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#list_paragraph</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#markdown_block</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#separator</string>
								</dict>
							</array>
							<key>while</key>
							<string>\G([ ]{4}|\t|$)</string>
						</dict>
					</array>
				</dict>
				<key>madoko_float</key>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>^\s*([~]+)\s*(TexRaw)</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.heading.4.markdown</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\1\n</string>
							<key>name</key>
							<string>madoko.float.texraw.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>text.tex.embed</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>^\s*([~]+)\s*([A-Z]\w+)</string>
							<key>beginCaptures</key>
							<dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>markup.heading.4.markdown</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>meta.floatdata.markdown</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\1\n</string>
							<key>name</key>
							<string>madoko.float.markdown</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>begin</key>
									<string>(^|\G)(\|)</string>
									<key>name</key>
									<string>markup.raw.block.table.markdown</string>
									<key>while</key>
									<string>(^|\G)(\|)</string>
								</dict>
								<dict>
									<key>begin</key>
									<string>\{</string>
									<key>beginCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.brace.markdown</string>
										</dict>
									</dict>
									<key>end</key>
									<string>\}</string>
									<key>endCaptures</key>
									<dict>
										<key>0</key>
										<dict>
											<key>name</key>
											<string>punctuation.definition.brace.markdown</string>
										</dict>
									</dict>
									<key>name</key>
									<string>meta.floatdata.markdown</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>begin</key>
											<string>([\w_-]+)(=)(")</string>
											<key>beginCaptures</key>
											<dict>
												<key>1</key>
												<dict>
													<key>name</key>
													<string>variable.floatdata.markdown</string>
												</dict>
												<key>2</key>
												<dict>
													<key>name</key>
													<string>keyword.operator.markdown</string>
												</dict>
												<key>3</key>
												<dict>
													<key>name</key>
													<string>string.quoted.markdown</string>
												</dict>
											</dict>
											<key>contentName</key>
											<string>string.quoted.markdown</string>
											<key>end</key>
											<string>"</string>
											<key>endCaptures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>string.quoted.markdown</string>
												</dict>
											</dict>
											<key>name</key>
											<string>meta.floatdata.entry.markdown</string>
											<key>patterns</key>
											<array>
												<dict>
													<key>include</key>
													<string>#inline</string>
												</dict>
											</array>
										</dict>
										<dict>
											<key>captures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>constant.other.symbol.id.markdown.mdk</string>
												</dict>
											</dict>
											<key>match</key>
											<string>\#[\w_\-:.]+</string>
											<key>name</key>
											<string>meta.floatdata.symbol.markdown</string>
										</dict>
										<dict>
											<key>captures</key>
											<dict>
												<key>0</key>
												<dict>
													<key>name</key>
													<string>constant.other.symbol.id.markdown.mdk</string>
												</dict>
											</dict>
											<key>match</key>
											<string>\@[\w_\-:.]+</string>
											<key>name</key>
											<string>meta.floatdata.symbol.markdown</string>
										</dict>
									</array>
								</dict>
								<dict>
									<key>include</key>
									<string>#inline</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#embedded_code</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#madoko_float</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#raw_block_github</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#lists</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<key>paragraph</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)(?=\S)</string>
					<key>name</key>
					<string>meta.paragraph.markdown</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#inline</string>
						</dict>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#separator</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#raw_block_github</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#madoko_float</string>
						</dict>
					</array>
					<key>while</key>
					<string>(^|\G)(?!\s*$|#|[ ]{,3}([-*_][ ]{2,}){3,}[ \t]*$\n?|\s*\[.+?\]:|&gt;)</string>
				</dict>
				<key>raw_block</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([ ]{4}|\t)</string>
					<key>name</key>
					<string>markup.raw.block.markdown</string>
					<key>while</key>
					<string>(^|\G)([ ]{4}|\t)</string>
				</dict>
				<key>raw_block_github</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)\s*[`~]{3,}.*\n</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.raw.border.markdown</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>markup.raw.block.markdown</string>
					<key>end</key>
					<string>[`~]{3,}\n</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>markup.raw.border.markdown</string>
						</dict>
					</dict>
				</dict>
				<key>separator</key>
				<dict>
					<key>match</key>
					<string>@@@(^|\G)[ ]{,3}([-*_])([ ]{,2}\2){2,}[ \t]*$\n?</string>
					<key>name</key>
					<string>meta.separator.markdown</string>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>markdown.gfmd</string>
	<key>uuid</key>
	<string>0532381A-25F1-46A3-A39E-C792801A259B</string>
</dict>
</plist>
