<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>mdk</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~K</string>
	<key>name</key>
	<string>Madoko</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#paragraph</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#blocks</string>
		</dict>
		<dict>
			<key>include</key>
			<string>markdown.gfmd</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blocks</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attributes.markdown.mdk</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.attributes.markdown.mdk</string>
						</dict>
					</dict>
					<key>name</key>
					<string>attributes.markdown.mdk</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>paragraph</key>
		<dict>
			<key>begin</key>
			<string>(^|\G)(?=\S)</string>
			<key>name</key>
			<string>meta.paragraph.markdown.mdk</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blocks</string>
				</dict>
				<dict>
					<key>include</key>
					<string>markdown.gfmd</string>
				</dict>
			</array>
			<key>while</key>
			<string>(^|\G)(?!\s*$|#|[ ]{,3}([-*_][ ]{2,}){3,}[ \t]*$\n?|\s*\[.+?\]:|&gt;)</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>markdown.mdk</string>
	<key>uuid</key>
	<string>21E01B95-768E-41EB-9FFD-B77F4D0D3CA0</string>
</dict>
</plist>
