<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
	</array>
	<key>name</key>
	<string>Tex Embedded</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\\\w+</string>
			<key>name</key>
			<string>support.function.tex</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^[ \t]+)?(?=%)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.whitespace.comment.leading.tex</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?!\G)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>%:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.semicolon.texshop.tex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(%!TEX) (\S*) =</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.directive.texshop.tex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>%</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.tex</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.percentage.tex</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.tex.embed</string>
	<key>uuid</key>
	<string>8857220C-4DA3-4B68-9681-D2306E99ECC0</string>
</dict>
</plist>
